import Head from "next/head";
import { useTranslation } from "react-i18next";
import i18n from "i18next";

export default function Home() {
  const { t } = useTranslation("Common");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{t("testH1")}</h1>
      <button onClick={() => i18n.changeLanguage("ja")}>日本語</button>
      <button onClick={() => i18n.changeLanguage("en")}>英語</button>
    </>
  );
}
